### PR TITLE
Add AbstractTerminalPanel for simple adding terminal on JFrame

### PR DESCRIPTION
**Pull request by nikdevsirotenko**
A separate class for embedding panels in a frame

### CODE REVIEW

**Comment by segrey** [comment]
As I can see, this PR introduces another abstraction layer over existing API and wraps `myTerminal.getComponent()` into `JPanel`.
What are the benefits of this change?

Actually, `AbstractTabbedTerminalWidget` is going to be deprecated, `com.jediterm.terminal.ui` package will contain only basic/necessary UI.

Probably, it'd be better to have such utility code on a client, not in jediterm.

**Comment by nikdevsirotenko** [comment]
Yes you right, i see now how realize in intellij idea. I created this class 
for further simple working with changing sizes how terminal like that  JPanel, because when I added it to the panel in this way, it set a hard size)

**Comment by nikdevsirotenko** [comment]
@segrey 
yes, you’re right, I created this class to improve the work with resizing later, because when I added it via getComponent, the sizes are set rigidly and when adding other elements inside, it did not change its size, but simply cut off on the sides)

**Comment by nikdevsirotenko** [comment]
@segrey 
What improvement can be worked on in the terminal?

**Comment by segrey** [comment]
@nikdevsirotenko Feel free to work on any improvement you want. Please make sure there is an issue describing a bug/feature you're working on. Create one if there is no such issue.

**Pull request closed without merging**
