### PR TITLE
Remove log4j dependency on latest Java 8 compatible release

### PR DESCRIPTION
**Pull request by Plonk42**
More CVEs have been found for Log4j 1.x and for some business reasons we are still running on Java 8, so upgrading to latest JediTerm is sadly not an option (requiring Java 11).

This PR is a quick and dirty proposal to remove the dependency to `log4j` and replace it with plain `java.util.logging`, based on the latest version of JediTerm running with Java 8.

### CODE REVIEW

**Comment by segrey** [comment]
IIUC, you're going to use 212 branch until it's possible for you to update to Java 11, right?

**Comment by segrey** [comment]
BTW, log4j dependency has been already dropped in master (https://github.com/JetBrains/jediterm/commit/24d171d69e85c02b9ee5d37febd37b46829099d9).

**Comment by Plonk42** [comment]
> IIUC, you're going to use 212 branch until it's possible for you to update to Java 11, right?

Correct. Hopefully in not too long...

> BTW, log4j dependency has been already dropped in master (24d171d).

Yes, I was happy to see that until I realize we cannot simply upgrade to the latest master (because of Java 11).

Thanks for merging!

**Comment by segrey** [comment]
@Plonk42 In future we're planning to move this project (jediterm) from LGPLv3 licence to Apache 2.0 only. Are you OK with that? You contributed a lot to this project.

**Comment by Plonk42** [comment]
Hello @segrey, yes I'm OK with Apache 2.0 only. 

Sorry for the long delay, I had to check with the legal team...

Thanks for maintaining JediTerm!

**Comment by antimatter84** [comment]
> BTW, log4j dependency has been already dropped in master ([24d171d](https://github.com/JetBrains/jediterm/commit/24d171d69e85c02b9ee5d37febd37b46829099d9)).

Where can I find the latest release of jediterm? mvnrepository.com lists version 2.42 from March 2019 which still contains the log4j dependency.

Thanks.

**Pull request merged**
