### PR TITLE
Support 2-bytes string termination for system commands

### LINKED ISSUE #185: 2-bytes ST not recognized as system command termination
`SystemCommandSequence` does recognize only the C1 control code `0x9C` or the `BEL` character as the OSC termination, but fails to parse the 2-bytes sequence `ESC \` not resetting the terminal status.

The sequence to print a text with a link

```sh
$ echo -e '\x1B]8;;http://example.org\x1B\\Test link\x1B]8;;\x1B\\ Test test'
```

produces `Test link Test test` (with hyperlink upon "Test link") on iTerm, but nothing on jediterm, whereas `Test link Test test` was expected as the `ST` sequence is present just before the first text.

In running processes using the ST sequence this will block the output until the process exits.

### PR DESCRIPTION
**Pull request by alekitto**
Fixes #185

### CODE REVIEW

**Comment by enumag** [comment]
bump

**Comment by enumag** [comment]
ping @segrey @traff

**Comment by segrey** [comment]
@alekitto Thank you for the PR! I've changed it and pushed as https://github.com/JetBrains/jediterm/commit/9776866a4d64bc5a1fa290159c8b9028baef39bd.

**Comment by enumag** [comment]
@segrey So this should make it possible to print links into the terminal, right? Any idea which version of PHPStorm could this change land into?

**Comment by segrey** [comment]
@enumag Not yet, but the work is in progress (https://github.com/JetBrains/jediterm/commit/9b637fad110a96612ae95b3872861aded3fd062f). I'll update https://youtrack.jetbrains.com/issue/IDEA-204536 when the fix version is clear (likely, it will be the next week).

**Pull request closed without merging**
